//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.ProjectDetailsReaderTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.ProjectDetailsReaderTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dependencies&quot;: {
        ///    &quot;Reference1.Data&quot;: &quot;1.0.0&quot;,
        ///    &quot;Reference2.Logic&quot;: &quot;2.0.0&quot;,
        ///    &quot;Reference3.Service&quot;: &quot;3.0.0&quot;
        ///  },
        ///  &quot;frameworks&quot;: {
        ///    &quot;net48&quot;: {}
        ///  },
        ///  &quot;runtimes&quot;: {
        ///    &quot;win-anycpu&quot;: {},
        ///    &quot;win&quot;: {}
        ///  }
        ///}.
        /// </summary>
        internal static string PackagesFile {
            get {
                return ResourceManager.GetString("PackagesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup Label=&quot;Globals&quot;&gt;
        ///    &lt;SccProjectName&gt;SAK&lt;/SccProjectName&gt;
        ///    &lt;SccProvider&gt;SAK&lt;/SccProvider&gt;
        ///    &lt;SccAuxPath&gt;SAK&lt;/SccAuxPath&gt;
        ///    &lt;SccLocalPath&gt;SAK&lt;/SccLocalPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFrameworks&gt;netstandard2.0;net461&lt;/TargetFrameworks&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Version&gt;0.1.4&lt;/Version&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string ProjectFileInDotNetStandard {
            get {
                return ResourceManager.GetString("ProjectFileInDotNetStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;15.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProjectGuid&gt;{B2A76D41-E1C6-4F9A-B064-AF428A88E97F}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///    &lt;RootNamespace&gt;DependencyScannerTess&lt;/RootName [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectFileWithAssemblyName {
            get {
                return ResourceManager.GetString("ProjectFileWithAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;15.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProjectGuid&gt;{B2A76D41-E1C6-4F9A-B064-AF428A88E97F}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///    &lt;RootNamespace&gt;DependencyScannerTess&lt;/RootName [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectFileWithoutAssemblyName {
            get {
                return ResourceManager.GetString("ProjectFileWithoutAssemblyName", resourceCulture);
            }
        }
    }
}
